language: ruby

rvm:
  - 1.9.3

before_script:
 - mkdir ~/.task
 - echo data.location=~/.task > ~/.taskrc

before_install:
 - sudo apt-get update
 - sudo apt-get install task
 - sudo apt-get install graphviz
